#
# Makefile for sciaps miscellaneous devices
#

obj-$(CONFIG_SCIAPS_DRIVERS)	+= ti-dac7513-spi.o ti-ads7841-spi.o lt-ltc1658-spi.o ti-tpl0501-spi.o sciaps-cntlr-i2c.o
#obj-$(CONFIG_SCIAPS_TI_DAC7513_SPI)	+= ti-dac7513-spi.o
#obj-$(CONFIG_SCIAPS_TI_ADS7841_SPI)	+= ti-ads7841-spi.o
